### ISSUE TITLE
Allow additional `className`s for progress bar div.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [KaterinaLupacheva/react-progress-bar#14]
## What I want to do
I want to change the style of the progress bar to be `cursor: pointer` (using `className` with external css). 

## What I considered doing
I don't want to wrap the component inside another div like in #5:
```jsx
<div className='myClassName'>
  <ProgressBar />
</div>
```
This creates an extra `div` tag, which is unnecessary.
 
### `className` prop
The given `className` can be passed to the div.
```jsx
<ProgressBar className='myClassName' />
```

### `divProps` prop
This allows more customization for the `div` props.
```jsx
<ProgressBar divProps={{ className: 'myClassName' }} />
```

- [x] I can make a pull request for this issue

**Comment by KaterinaLupacheva** [comment]
@ChocolateLoverRaj could you please make a pull request?

**Comment by ChocolateLoverRaj** [comment]
@KaterinaLupacheva I will make a pr.
