### ISSUE TITLE
Code style: standard?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [KaterinaLupacheva/react-progress-bar#19]
In `README.md` there is a badge that says code style: standard. However, the files are not using StandardJs.

The `ts-standard` eslint config should be added to `.eslintrc` and the files should use that, so that the badge makes sense.

Or you could remove the badge so that contributors know that it's *not* using standard.

- [x] I can make a PR for this.

**Comment by KaterinaLupacheva** [comment]
@ChocolateLoverRaj it would be really helpful if you could make a PR for this.
