### ISSUE TITLE
Passing a class directly for the bar component

### ISSUE THREAD

**Issue by kreonjr** [KaterinaLupacheva/react-progress-bar#43]
Hi there! Thanks for an awesome and simple progress bar component!

I was wondering if there is any current way (or any plan to support) passing a class name with some css properties that will apply directly to the bar instead of its wrapping div?

The need for this ask comes from supporting light/dark mode and the variable properties are generated inside an scss file so we don't have access to the correct color inside our component to pass it as a prop.

So instead of: 

```
<ProgressBar 
  className={"container-styles"} 
  completed="50"
  bgColor="white" 
  baseBgColor="red" 
  width="200px" 
  height="6px"
/>
```

you could also do something like:

```
<ProgressBar 
  className={"container-styles"} 
  barClassName={"bar-styles"} 
  completed="50" 
  isLabelVisible={false} 
/>
```

where 'bar-styles' would be applied to the colors, width, height etc of the bar itself. i.e.
```
.bar-styles {
  color: "white";
  background-color: "red";
  height: "6px";
  width: "200px";
}
```

**Comment by KaterinaLupacheva** [comment]
Hi! First of all, thank you for your nice words! 

As for your suggestion, well, I see your point and understand your use case. The only implementation problem (for me, to update the library) is may come from the fact that the bar itself consists of 3 divs: wrapper, full-width bar (with `baseBgColor`), and the completed part. So probably there should be not only `barClassName` prop which will be applied to the completed part (with `bgColor` prop currently), but also the separate className prop for the part with the `baseBgColor`.

Thank you for your suggestion! I'll try to make the updates as soon as I have a couple of free hours:)

**Comment by kreonjr** [comment]
Thank you so much for your response. And thank you so much for getting a fix in for this so quickly. This will make using your library 100 times easier for us and I really appreciate it. Awesome work

**Comment by KaterinaLupacheva** [comment]
Thank you very much! If I get a request to add any feature to the library, I try my best to respond as quickly as I can. And if there is a use case for custom class names, I do hope it will make using the library easier:)

**Comment by iefraim** [comment]
so i tried doing that
`<ProgressBar
              completed={Math.round((totalDonations / props.item.goal) * 100)}
              completedClassName="barCompleted"
              barContainerClassName="barUncompleted"
            />`
`
.barCompleted {
  background-color: $primary;
}
.barUncompleted {
  background-color: $secondary;
}`
but this is what i got:
![image](https://github.com/KaterinaLupacheva/react-progress-bar/assets/74383772/76e844db-49f4-4cff-af33-0f5027e70c19)
when i remove the completedClassName, i get:
![image](https://github.com/KaterinaLupacheva/react-progress-bar/assets/74383772/452c3df7-4958-49bf-961b-57d20254b851)
can you please fix this? thanks!
