### ISSUE TITLE
Is there way to do a gradient bar color?

### ISSUE THREAD

**Issue by raymolla7** [KaterinaLupacheva/react-progress-bar#45]
Hi, I love this progress bar but I am wondering is there any way to do a gradient bgColor?

Something like this: `'linear-gradient(to right, rgba(242,158,76,0.85), rgba(241,196,83,0.8)'`

Thanks, 

Ray

**Comment by KaterinaLupacheva** [comment]
Hi Ray! Yes, you can use gradient colors as a background (both for bgColor and for baseBgColor) starting from v4.3.0.

1. upgrade @ramonak/react-progress-bar to the version 4.3.0
2. Change bgColor prop:
```
<ProgressBar 
    completed={50}
    bgColor="linear-gradient(to right, rgba(242,158,76,0.85), rgba(241,196,83,0.8))"
    />
```

**Comment by raymolla7** [comment]
Thank you so much!
