### ISSUE TITLE
Start Bar Animation from a certain percentage

### ISSUE THREAD

**Issue by raymolla7** [KaterinaLupacheva/react-progress-bar#46]
I am using the Animate On Render functionality, but it always animates starting from 0%. 

Is there a way to animate it starting from a percentage like 50% going to 100%?

**Comment by KaterinaLupacheva** [comment]
@raymolla7 I added a new prop to the Progress bar component - `initCompletedOnAnimation`. The value of this prop is the starting point (e.g. completed width) when animateOnRender is true.

```
<ProgressBar completed={100} animateOnRender initCompletedOnAnimation={50}/>
```

The progress bar will start from 50% and go up to 100% with animation.

Please don't forget to upgrade to the latest version of the @ramonak/react-progress-bar library - v4.4.0

**Comment by raymolla7** [comment]
You are amazing, thank you!
