### ISSUE TITLE
 I want to pass to the ProgressBar container className <div style = {outsideStyles}> or add attribute fullWidth

### ISSUE THREAD

**Issue by BykovDenis** [KaterinaLupacheva/react-progress-bar#5]
The progress bar is inside the flex-container flex: column.
The progress bar stretches to its full width if you pass the flex-grow: 1. But i can't to pass any css class

**Comment by KaterinaLupacheva** [comment]
@BykovDenis could you please explain specifically what you are trying to achieve? There is a "width" prop present for the progress bar, which defined its length, basically. Which css prop would you like to pass?

**Comment by KaterinaLupacheva** [comment]
@BykovDenis if you need to pass flex-grow: 1 to the Progress Bar, you can add a wrapper (parent) div and set its flex-grow: 1. The progress bar will fit the width of the parent component. Like this:

```jsx
<div style={{ flexGrow: 1 }}>
      <ProgressBar completed={50} />
</div>
```

Or with a class name:
//styles.css

.pb {
  flex-grow: 3;
}

//App.js

<div className="pb">
      <ProgressBar completed={50} />
</div>

**Comment by BykovDenis** [comment]
Thanks it works
