### ISSUE TITLE
Keep styles in DOM nodes

### ISSUE THREAD

**Issue by kla-ko** [KaterinaLupacheva/react-progress-bar#68]
react-progress-bar is generating DOM nodes with ``style`` attributes, like
```html
<div style="height: 2em; background: rgb(224, 224, 222); border-radius: 1em; width: 100%; overflow: hidden;"><div>
```
When assigning one of the class-Props, like ``barContainerClassName``, the style attributes are completely replaced by the class attribute. Therefore, I have to put all these style attributes in my custom class. Further, more important, the style-like attributes which are passed as Props (like ``borderRadius``, or ``bgcolor``) are ignored when working with a custom class.

As a suggestion: keep the ``style`` attribute and add the ``class``-attribute in addition. Then, I can use the class to set css attributes which are not used as ``style``-attributes.

Regards,

**Comment by KaterinaLupacheva** [comment]
Hey @kla-ko! 
I see your point. But the idea of having custom classes for different parts of the progress bar was explicitly born for use cases when a user (developer) needs to override completely default library styles.
Re your suggestion "to keep the style attribute and add the class attribute in addition": I'm not sure that it will work as inline styles (the style attribute) will always override the styles in the class attribute. Or did I misunderstand your idea?

**Comment by kla-ko** [comment]
Hi @KaterinaLupacheva ,
Yes you are right! Inline styles have a higher priority. So my suggestion wouldn't work. Maybe, things get more flexible if a default class is used instead of the inline styles.

Thanks and best regards,
