### ISSUE TITLE
Hide label from progress bar

### ISSUE THREAD

**Issue by Ramanpreet6262** [KaterinaLupacheva/react-progress-bar#7]
Is there a way to hide the label and show only progress bar.

**Comment by KaterinaLupacheva** [comment]
@Ramanpreet6262 Currently there might be only a workaround for this: make a label and progress bar of the same color. But I'll add an additional prop so it would be possible to hide the label. Hope I'll have time for this in a couple of days

**Comment by Ramanpreet6262** [comment]
@KaterinaLupacheva Yes, I did that but when progress is around 5% or less, the label gets outside from left side as label alignment was by default right.
So currently, I fixed this by setting label alignment to outside and made the color of label same as outside background.

Ok thanks, sure please.
