### ISSUE TITLE
Indeterminate state

### ISSUE THREAD

**Issue by MarcoB89** [KaterinaLupacheva/react-progress-bar#81]
With this library is possible handle the indeterminate state of the progress bar? I didn't see nothing about it in the documentation....
If not could be a great plus add it.
Here the spec about the indeterminate state of the html progress: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

**Comment by KaterinaLupacheva** [comment]
@MarcoB89 `isIndeterminate` prop has been added

**Comment by KaterinaLupacheva** [comment]
Closed
