### ISSUE TITLE
isLableVisible prop not working.

### ISSUE THREAD

**Issue by nanadjei** [KaterinaLupacheva/react-progress-bar#9]
Trying to hide the label but it seems not to work.

``` isLableVisible={false} ```

**Comment by KaterinaLupacheva** [comment]
@nanadjei could you please check that you are using the latest version of the @ramonak/react-progress-bar? This prop was added only in the latest release - v.2.1.2

**Comment by raivis-km** [comment]
There's a small typo in readme file. I created PR.
@nanadjei use prop name isLabelVisible

**Comment by KaterinaLupacheva** [comment]
@raivis-km thank you very much! Nice catch!

**Comment by KaterinaLupacheva** [comment]
Closed
